version: '3.8'

services:
  app:
    container_name: application
    build: application
    network_mode: "host"
    restart: always
    command: uvicorn main:app --host 127.0.0.1 --port 8001 --reload
    volumes:
      - ./application:/usr/src/app
    environment:
      - TZ=Ho_Chi_Minh
    env_file:
      - .env
    ports:
      - 8001:8001
    # networks:
    #   - default
