version: '3.8'

services:
  app:
    container_name: api.tranduythien.net
    image: img_api_tranduythien
    build: app
    # network_mode: "host"
    restart: always
    command: uvicorn main:app --host 0.0.0.0 --port 8001 --reload
    volumes:
      - ./app:/usr/src/app
    environment:
      - TZ=Ho_Chi_Minh
    env_file:
      - .env
    ports:
      - 8001:8001
